### ISSUE TITLE
dh:ssh how is it used

### ISSUE THREAD

**Issue by Rawne** [cloudcastle/dockhero-cli#20]
just running it without parameters doesn't work, It gives me an ENOENT error, both on windows and ubuntu.

**Comment by vovayartsev** [comment]
Hi @Rawne 

Is this still an issue with the latest CLI plugin? You need a local `ssh` binary on your machine - please confirm you have one, then try launching the CLI plugin with  debugging headers turned ON as explained [here](https://devcenter.heroku.com/articles/developing-cli-plugins#debugging-tips)

PS: `dh:ssh` command will be removed soon

**Comment by Rawne** [comment]
hi @vovayartsev sorry for not responding! I did not see the notification. I'll close the issue, since i found a way to work around it back then, i might not have had the ssh binary availlable like you said. Thanks for your reply!

**Comment by vovayartsev** [comment]
@Rawne Thanks :-)
