### ISSUE TITLE
Heroku DockHero does not mount files, only empty folders

### ISSUE THREAD

**Issue by vinhloc30796** [cloudcastle/dockhero-cli#31]
Problem: `heroku dh:docker run --rm -v $(pwd):/config alpine ls -R /config` will show only folders, not files.
Expected: mounting should also mount files

**Comment by vovayartsev** [comment]
Hi Loc!

The thing which confused you is that under the hood, the `docker` command is executed on a remote host, while `$(pwd):/config` is resolved on your local machine.

e.g. `$(pwd):/config` could be `/home/loc/my-project/config`, while on the remote host there's simply no such folder, and Docker daemon there creates an empty folder.

the usual practice here is:
* for any information from your computer which you want to take to the remote machine, make it a part of Docker Build.
* for any persistent file storage use [docker volumes](https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference) with `local` driver (default). Also, these volumes are backed up daily (backups are not available on Hobby plan)

**Comment by vovayartsev** [comment]
Closing it because that's not an issue
